import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])), money=v=>Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2}), today=()=>new Date().toISOString().slice(0,10);
const DEFAULT_URL="https://YOUR-PROJECT.supabase.co";
const DEFAULT_KEY="YOUR_SUPABASE_PUBLISHABLE_OR_ANON_KEY";
const saved=JSON.parse(localStorage.getItem("bedbox_supabase_config")||"null")||{};
let SUPABASE_URL=saved.url||DEFAULT_URL, SUPABASE_ANON_KEY=saved.key||DEFAULT_KEY;
let sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); let user=null, profile=null, state={students:[],rooms:[],beds:[],payments:[],expenses:[],profiles:[]};
const role=()=>profile?.role||"staff", isManager=()=>["manager","admin"].includes(role()), isAdmin=()=>role()==="admin";

$("setupBtn").onclick=showSetup;
$("setupCancel").onclick=hideSetup;
$("setupSave").onclick=saveSetup;
$("loginBtn").onclick=login; $("logoutBtn").onclick=async()=>{await sb.auth.signOut()}; $("refreshBtn").onclick=refreshAll; $("password").onkeydown=e=>e.key==="Enter"&&login();
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page,b));
function configured(){return SUPABASE_URL!==DEFAULT_URL && SUPABASE_ANON_KEY!==DEFAULT_KEY && SUPABASE_URL.startsWith("https://")}
function showSetup(){$("setup").classList.remove("hidden");$("setupUrl").value=SUPABASE_URL===DEFAULT_URL?"":SUPABASE_URL;$("setupKey").value=SUPABASE_ANON_KEY===DEFAULT_KEY?"":SUPABASE_ANON_KEY}
function hideSetup(){$("setup").classList.add("hidden")}
function saveSetup(){const url=$("setupUrl").value.trim().replace(/\/$/,""),key=$("setupKey").value.trim();if(!url.startsWith("https://")||!key)return msg("Enter your Supabase Project URL and Publishable/Anon key.",true);localStorage.setItem("bedbox_supabase_config",JSON.stringify({url,key}));location.reload()}
function msg(t,error=false){$("loginMsg").textContent=t;$("loginMsg").className="notice"+(error?" error":"")}
async function login(){if(!configured())return msg("First click Setup and enter your Supabase Project URL + Publishable/Anon key.",true);const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return msg("Email and password are required.",true);msg("Signing in…");const {error}=await sb.auth.signInWithPassword({email,password});if(error)msg(error.message,true)}
async function boot(session){user=session?.user||null;if(!user){$("login").classList.remove("hidden");$("app").classList.add("hidden");return}const {data:p,error}=await sb.from("profiles").select("*").eq("id",user.id).single();if(error||!p||!p.role){await sb.auth.signOut();return msg("Your account has no BedBox staff role. Ask an administrator.",true)}profile=p;$("login").classList.add("hidden");$("app").classList.remove("hidden");$("userBox").innerHTML=`<b>${esc(user.email)}</b>${esc(role().toUpperCase())}`;document.querySelectorAll("[data-admin-only]").forEach(x=>x.classList.toggle("hidden",!isAdmin()));await refreshAll();showPage("dashboard",document.querySelector('[data-page="dashboard"]'))}
if(!configured()) showSetup();
sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>boot(s),0));sb.auth.getSession().then(({data})=>boot(data.session));

async function rows(table,order="created_at"){let q=sb.from(table).select("*");if(order)q=q.order(order,{ascending:false});const {data,error}=await q.limit(1000);if(error){console.error(table,error);return[]}return data||[]}
async function refreshAll(){const [students,rooms,beds,payments,expenses]=await Promise.all([rows("students"),rows("rooms"),rows("beds"),rows("payments","date"),rows("expenses","date")]);state={...state,students,rooms,beds,payments,expenses};if(isAdmin())state.profiles=await rows("profiles");}
function showPage(page,b){document.querySelectorAll("[data-page]").forEach(x=>x.classList.remove("active"));b?.classList.add("active");$("title").textContent=({rooms:"Rooms & Beds",students:"Students",payments:"Payments",expenses:"Expenses",reports:"Reports",staff:"Staff"}[page]||"Dashboard");const f={dashboard:dashboard,students:studentsPage,rooms:roomsPage,payments:paymentsPage,expenses:expensesPage,reports:reportsPage,staff:staffPage};$("content").innerHTML=(f[page]||dashboard)();}
window.showPage=showPage;
function dashboard(){const occ=state.beds.filter(b=>b.status==="Occupied").length,paid=state.payments.filter(p=>p.status==="Paid").reduce((a,x)=>a+Number(x.amount),0),due=state.payments.filter(p=>p.status==="Due").reduce((a,x)=>a+Number(x.amount),0),ex=state.expenses.reduce((a,x)=>a+Number(x.amount),0);return `<div class="grid"><div class="card stat">Students<b>${state.students.length}</b></div><div class="card stat">Occupancy<b>${occ}/${state.beds.length}</b></div><div class="card stat">Outstanding<b>₹${money(due)}</b></div><div class="card stat">Net cash<b>₹${money(paid-ex)}</b></div></div><div class="card section"><h3>Quick actions</h3><div class="actions"><button class="btn primary" onclick="openStudent()">Add Student</button><button class="btn" onclick="openRoom()">Add Room</button><button class="btn" onclick="openBed()">Add Bed</button><button class="btn" onclick="openPayment()">Record Payment</button><button class="btn" onclick="openExpense()">Add Expense</button></div></div>`}
const selStudents=id=>state.students.map(s=>`<option value="${s.id}" ${s.id===id?"selected":""}>${esc(s.name)} — ${esc(s.phone)}</option>`).join(""), selRooms=id=>state.rooms.map(r=>`<option value="${r.id}" ${r.id===id?"selected":""}>Room ${esc(r.number)}</option>`).join("");
function studentsPage(){return `<div class="card"><div class="toolbar"><div><h3>Students</h3><div class="muted">${state.students.length} residents</div></div><div><input id="studentSearch" class="search" placeholder="Search" oninput="renderStudents(this.value)"> <button class="btn primary" onclick="openStudent()">+ Add Student</button></div></div><div id="studentTable">${studentTable()}</div></div>`}
function studentTable(filter=""){const a=state.students.filter(s=>`${s.name} ${s.phone} ${s.room||""} ${s.bed||""}`.toLowerCase().includes(filter.toLowerCase()));return `<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Course</th><th>Room / Bed</th><th>Join date</th><th>Actions</th></tr></thead><tbody>${a.map(s=>`<tr><td><b>${esc(s.name)}</b><br>${esc(s.guardian||"")}</td><td>${esc(s.phone)}</td><td>${esc(s.course||"-")}</td><td>${esc(s.room||"-")} / ${esc(s.bed||"-")}</td><td>${esc(s.join_date)}</td><td class="row-actions"><button class="btn small" onclick="openStudent('${s.id}')">Edit</button><button class="btn small" onclick="openAllocation('${s.id}')">Allocate</button>${s.bed_id?`<button class="btn small" onclick="releaseBed('${s.id}')">Release</button>`:""}${isManager()?`<button class="btn small danger" onclick="deleteStudent('${s.id}')">Delete</button>`:""}</td></tr>`).join("")||`<tr><td colspan="6" class="empty">No students found.</td></tr>`}</tbody></table></div>`}
window.renderStudents=f=>$("studentTable").innerHTML=studentTable(f);
function roomsPage(){return `<div class="toolbar"><div class="muted">${state.rooms.length} rooms • ${state.beds.length} beds</div><div><button class="btn primary" onclick="openRoom()">+ Add Room</button>${isManager()?`<button class="btn" onclick="openBed()">+ Add Bed</button>`:""}</div></div><div class="roomgrid">${state.rooms.map(r=>{const bs=state.beds.filter(b=>b.room_id===r.id);return `<div class="card roomcard"><h3>Room ${esc(r.number)}</h3><div class="muted">${esc(r.type)} • ${bs.length}/${r.capacity}</div><div class="bedgrid">${bs.map(b=>`<div class="bed ${b.status==='Available'?'available':''}" ${b.status==='Available'?`onclick="openAllocationByBed('${b.id}')"`:''}><b>${esc(b.label)}</b><small>${esc(b.status)}</small><small>${esc(b.student_name||"")}</small></div>`).join("")||`<div class="empty">No beds</div>`}</div>${isManager()?`<button class="btn small" onclick="openRoom('${r.id}')">Edit room</button>`:""}</div>`}).join("")||`<div class="card empty">Create your first room.</div>`}</div>`}
function paymentsPage(){return `<div class="card"><div class="toolbar"><div><h3>Payment history</h3><div class="muted">${state.payments.length} records</div></div><button class="btn primary" onclick="openPayment()">+ Record Payment</button></div>${paymentTable()}</div>`}
function paymentTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Student</th><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th><th>Recorded by</th><th>Actions</th></tr></thead><tbody>${state.payments.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.student_name||"")}</td><td>₹${money(p.amount)}</td><td>${esc(p.method)}</td><td>${esc(p.reference||"-")}</td><td><span class="badge ${p.status==='Paid'?'paid':'due'}">${p.status}</span></td><td>${esc(p.recorded_by_email||"-")}</td><td><button class="btn small" onclick="openPayment('${p.id}')">Edit</button>${isAdmin()?`<button class="btn small danger" onclick="deletePayment('${p.id}')">Delete</button>`:""}</td></tr>`).join("")||`<tr><td colspan="8" class="empty">No payment history.</td></tr>`}</tbody></table></div>`}
function expensesPage(){return `<div class="card"><div class="toolbar"><div><h3>Expenses</h3><div class="muted">${state.expenses.length} records</div></div><button class="btn primary" onclick="openExpense()">+ Add Expense</button></div>${expenseTable()}</div>`}
function expenseTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Vendor</th><th>Recorded by</th><th>Actions</th></tr></thead><tbody>${state.expenses.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.category)}</td><td>${esc(e.description)}</td><td>₹${money(e.amount)}</td><td>${esc(e.vendor||"-")}</td><td>${esc(e.recorded_by_email||"-")}</td><td><button class="btn small" onclick="openExpense('${e.id}')">Edit</button>${isAdmin()?`<button class="btn small danger" onclick="deleteExpense('${e.id}')">Delete</button>`:""}</td></tr>`).join("")||`<tr><td colspan="7" class="empty">No expenses.</td></tr>`}</tbody></table></div>`}
function reportsPage(){const paid=state.payments.filter(p=>p.status==='Paid').reduce((a,x)=>a+Number(x.amount),0),due=state.payments.filter(p=>p.status==='Due').reduce((a,x)=>a+Number(x.amount),0),ex=state.expenses.reduce((a,x)=>a+Number(x.amount),0),occ=state.beds.filter(b=>b.status==='Occupied').length;return `<div class="grid"><div class="card stat">Paid fees<b>₹${money(paid)}</b></div><div class="card stat">Due fees<b>₹${money(due)}</b></div><div class="card stat">Expenses<b>₹${money(ex)}</b></div><div class="card stat">Net<b>₹${money(paid-ex)}</b></div></div><div class="card section"><h3>Occupancy</h3><p>${occ} occupied of ${state.beds.length} beds (${state.beds.length?Math.round(occ/state.beds.length*100):0}%).</p></div>`}
function staffPage(){if(!isAdmin())return `<div class="card">Admin access required.</div>`;return `<div class="card"><div class="toolbar"><div><h3>Staff</h3><div class="muted">Roles are protected by database RLS.</div></div><button class="btn primary" onclick="openStaff()">Set role</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Email</th><th>Role</th><th>User ID</th></tr></thead><tbody>${state.profiles.map(p=>`<tr><td>${esc(p.email)}</td><td>${esc(p.role)}</td><td>${esc(p.id)}</td></tr>`).join("")}</tbody></table></div></div>`}
function modal(title,body){$("modalBody").innerHTML=`<div class="modalhead"><h2>${title}</h2><button class="btn" onclick="closeModal()">Close</button></div>${body}`;$("modal").classList.add("show")};window.closeModal=()=>$("modal").classList.remove("show");$("modal").onclick=e=>e.target===$("modal")&&closeModal();
window.openStudent=id=>{const s=state.students.find(x=>x.id===id)||{};modal(id?'Edit Student':'Add Student',`<div class="form"><div class="field"><label>Full name *</label><input id="sname" value="${esc(s.name)}"></div><div class="field"><label>Phone *</label><input id="sphone" value="${esc(s.phone)}"></div><div class="field"><label>Guardian</label><input id="sguardian" value="${esc(s.guardian)}"></div><div class="field"><label>Course / occupation</label><input id="scourse" value="${esc(s.course)}"></div><div class="field"><label>Join date</label><input id="sjoin" type="date" value="${esc(s.join_date||today())}"></div><div class="field"><label>Monthly rent</label><input id="srent" type="number" min="0" value="${esc(s.monthly_rent||0)}"></div><div class="field full"><label>Notes</label><textarea id="snotes">${esc(s.notes)}</textarea></div><div class="full"><button class="btn primary" onclick="saveStudent('${id||''}')">Save student</button></div></div>`)};
window.saveStudent=async id=>{const x={name:$("sname").value.trim(),phone:$("sphone").value.trim(),guardian:$("sguardian").value.trim(),course:$("scourse").value.trim(),join_date:$("sjoin").value||today(),monthly_rent:Number($("srent").value||0),notes:$("snotes").value.trim(),updated_by:user.id};if(!x.name||!x.phone)return alert("Name and phone are required");let r=id?await sb.from('students').update(x).eq('id',id):await sb.from('students').insert({...x,created_by:user.id});if(r.error)return alert(r.error.message);closeModal();await refreshAll();showPage('students',document.querySelector('[data-page="students"]'))};
window.deleteStudent=async id=>{if(!isManager()||!confirm('Delete this student record?'))return;const {error}=await sb.from('students').delete().eq('id',id);if(error)alert(error.message);else{await refreshAll();showPage('students',document.querySelector('[data-page="students"]'))}};
window.openRoom=id=>{const r=state.rooms.find(x=>x.id===id)||{};modal(id?'Edit Room':'Add Room',`<div class="form"><div class="field"><label>Room number *</label><input id="rnumber" value="${esc(r.number)}"></div><div class="field"><label>Type</label><input id="rtype" value="${esc(r.type||'Shared')}"></div><div class="field"><label>Capacity</label><input id="rcap" type="number" min="1" value="${esc(r.capacity||1)}"></div><div class="field"><label>Rent / bed</label><input id="rrent" type="number" min="0" value="${esc(r.rent||0)}"></div><div class="full"><button class="btn primary" onclick="saveRoom('${id||''}')">Save room</button></div></div>`)};
window.saveRoom=async id=>{const x={number:$("rnumber").value.trim(),type:$("rtype").value.trim()||'Shared',capacity:Number($("rcap").value||1),rent:Number($("rrent").value||0)};if(!x.number)return alert('Room number is required');let r=id?await sb.from('rooms').update(x).eq('id',id):await sb.from('rooms').insert({...x,created_by:user.id});if(r.error)return alert(r.error.message);closeModal();await refreshAll();showPage('rooms',document.querySelector('[data-page="rooms"]'))};
window.openBed=id=>{const b=state.beds.find(x=>x.id===id)||{};modal(id?'Edit Bed':'Add Bed',`<div class="form"><div class="field"><label>Room *</label><select id="broom">${selRooms(b.room_id)}</select></div><div class="field"><label>Bed label *</label><input id="blabel" value="${esc(b.label)}" placeholder="A1"></div><div class="full"><button class="btn primary" onclick="saveBed('${id||''}')">Save bed</button></div></div>`)};
window.saveBed=async id=>{const room=state.rooms.find(r=>r.id===$("broom").value),label=$("blabel").value.trim();if(!room||!label)return alert('Room and label are required');const x={room_id:room.id,label};let r=id?await sb.from('beds').update(x).eq('id',id):await sb.from('beds').insert({...x,created_by:user.id});if(r.error)return alert(r.error.message);closeModal();await refreshAll();showPage('rooms',document.querySelector('[data-page="rooms"]'))};
function allocBody(studentId,bedId){const avail=state.beds.filter(b=>b.status==='Available'||b.id===bedId);return `<div class="form"><div class="field full"><label>Student</label><select id="astudent">${selStudents(studentId)}</select></div><div class="field full"><label>Available bed</label><select id="abed">${avail.map(b=>`<option value="${b.id}" ${b.id===bedId?'selected':''}>Room ${esc(state.rooms.find(r=>r.id===b.room_id)?.number||'')} — ${esc(b.label)}</option>`).join('')}</select></div><div class="full"><button class="btn primary" onclick="allocateBed()">Confirm allocation</button></div></div>`}
window.openAllocation=id=>modal('Allocate room / bed',allocBody(id));window.openAllocationByBed=id=>modal('Allocate room / bed',allocBody('',id));window.allocateBed=async()=>{const {error}=await sb.rpc('allocate_bed',{p_student_id:$("astudent").value,p_bed_id:$("abed").value});if(error)alert(error.message);else{closeModal();await refreshAll();showPage('rooms',document.querySelector('[data-page="rooms"]'))}};window.releaseBed=async id=>{if(!confirm('Release this bed?'))return;const {error}=await sb.rpc('release_bed',{p_student_id:id});if(error)alert(error.message);else{await refreshAll();showPage('students',document.querySelector('[data-page="students"]'))}};
window.openPayment=id=>{const p=state.payments.find(x=>x.id===id)||{};modal(id?'Edit Payment':'Record Payment',`<div class="form"><div class="field full"><label>Student *</label><select id="pstudent"><option value="">Select</option>${selStudents(p.student_id)}</select></div><div class="field"><label>Amount *</label><input id="pamount" type="number" min="0.01" value="${esc(p.amount)}"></div><div class="field"><label>Status</label><select id="pstatus"><option ${p.status==='Paid'?'selected':''}>Paid</option><option ${p.status==='Due'?'selected':''}>Due</option></select></div><div class="field"><label>Date</label><input id="pdate" type="date" value="${esc(p.date||today())}"></div><div class="field"><label>Method</label><select id="pmethod">${['Cash','UPI','Bank Transfer','Card','Other'].map(m=>`<option ${p.method===m?'selected':''}>${m}</option>`).join('')}</select></div><div class="field"><label>Reference</label><input id="pref" value="${esc(p.reference)}"></div><div class="field full"><label>Note</label><textarea id="pnote">${esc(p.note)}</textarea></div><div class="full"><button class="btn primary" onclick="savePayment('${id||''}')">Save payment</button></div></div>`)};
window.savePayment=async id=>{const s=state.students.find(x=>x.id===$("pstudent").value),x={student_id:s?.id,student_name:s?.name,amount:Number($("pamount").value),status:$("pstatus").value,date:$("pdate").value||today(),method:$("pmethod").value,reference:$("pref").value.trim(),note:$("pnote").value.trim()};if(!s||x.amount<=0)return alert('Select student and valid amount');let r=id?await sb.from('payments').update(x).eq('id',id):await sb.from('payments').insert({...x,recorded_by:user.id,recorded_by_email:user.email});if(r.error)return alert(r.error.message);closeModal();await refreshAll();showPage('payments',document.querySelector('[data-page="payments"]'))};window.deletePayment=async id=>{if(!isAdmin()||!confirm('Delete payment?'))return;const {error}=await sb.from('payments').delete().eq('id',id);if(error)alert(error.message);else{await refreshAll();showPage('payments',document.querySelector('[data-page="payments"]'))}};
window.openExpense=id=>{const e=state.expenses.find(x=>x.id===id)||{};modal(id?'Edit Expense':'Add Expense',`<div class="form"><div class="field"><label>Date</label><input id="edate" type="date" value="${esc(e.date||today())}"></div><div class="field"><label>Category</label><select id="ecat">${['Maintenance','Electricity','Water','Food','Staff','Supplies','Other'].map(c=>`<option ${e.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input id="eamount" type="number" min="0.01" value="${esc(e.amount)}"></div><div class="field"><label>Vendor</label><input id="evendor" value="${esc(e.vendor)}"></div><div class="field full"><label>Description</label><input id="edesc" value="${esc(e.description)}"></div><div class="field full"><label>Note</label><textarea id="enote">${esc(e.note)}</textarea></div><div class="full"><button class="btn primary" onclick="saveExpense('${id||''}')">Save expense</button></div></div>`)};
window.saveExpense=async id=>{const x={date:$("edate").value||today(),category:$("ecat").value,amount:Number($("eamount").value),vendor:$("evendor").value.trim(),description:$("edesc").value.trim(),note:$("enote").value.trim()};if(x.amount<=0||!x.description)return alert('Valid amount and description are required');let r=id?await sb.from('expenses').update(x).eq('id',id):await sb.from('expenses').insert({...x,recorded_by:user.id,recorded_by_email:user.email});if(r.error)return alert(r.error.message);closeModal();await refreshAll();showPage('expenses',document.querySelector('[data-page="expenses"]'))};window.deleteExpense=async id=>{if(!isAdmin()||!confirm('Delete expense?'))return;const {error}=await sb.from('expenses').delete().eq('id',id);if(error)alert(error.message);else{await refreshAll();showPage('expenses',document.querySelector('[data-page="expenses"]'))}};
window.openStaff=()=>modal('Set staff role',`<div class="form"><div class="field full"><label>Supabase Auth user UUID</label><input id="fuid" placeholder="Paste user UUID"></div><div class="field full"><label>Role</label><select id="frole"><option>staff</option><option>manager</option><option>admin</option></select></div><div class="full"><button class="btn primary" onclick="setStaffRole()">Apply role</button></div></div>`);window.setStaffRole=async()=>{const {error}=await sb.rpc('set_staff_role',{p_user_id:$("fuid").value.trim(),p_role:$("frole").value});if(error)alert(error.message);else{closeModal();await refreshAll();showPage('staff',document.querySelector('[data-page="staff"]'))}};
